---
title: "Moisture trends in European peatlands - Circumpolar barplots"
author: "Laura Giese"
date: "8. Jan 2023"
output:
  html_document:
        dev: svglite
editor_options: 
  chunk_output_type: console
---

## Part 4
### This script shows results of our analysis of local NDWI trends of selected peatland sites (including insignificant trends) in Europe.

```{r, echo=T, eval=T, warning = F, message = F}
###-----------------------------------------------------------------###
###                          load libraries                         ###
###-----------------------------------------------------------------###

#devtools::install_github('renv')
#install.packages('renv')
#renv::init()
#renv::diagnostics()
options(vsc.plot = FALSE)
#setwd('/home/laurag/Arbeit/wwu/R/workspaces/satellite_ts_R/')
#install.packages('httpgd')
library(httpgd)
#install.packages('radian')

#library(remotes)
#install_github("r-spatial/sf")
library(rgeos)
library(sp)
#remotes::install_github("r-spatial/sf")
library(sf)
library(stars)
#install.packages('terra')
library(terra)
library(arrow)
#install.packages(svglite)
library(tidyverse)
#install.packages('cowplot')
library(cowplot)
#install.packages('libgdal')
library(tidyr)
#install.packages('rgdal')
library(purrr)
library(plyr)
library(dplyr)

library(stringr)
#install.packages('rowr')
#library(abind)
library(geojsonsf)
#install.packages('geojsonio')
library(geojsonio)

#install.packages('ggplot2')
library(ggplot2)
library(ggspatial)
#install.packages("ggpubr", repos = c("https://cran.rediris.org/", "https://cloud.r-project.org/"))
library(ggpubr)
#install.packages('plotly')
library(gridExtra)
library(plotly)
#install.packages('ggnewscale')
library(ggnewscale)

#devtools::install_github('ropenscilabs/rnaturalearthdata')
library(rnaturalearth)
library(rnaturalearthdata)
library('tidyterra')


senSlope <- function(formula, data, subset, na.action, intercept='Ac',
                     CI=.95) {
	# Coding History:
	#    2000Oct27 JRSlack  Original coding as kensen
	#    2011May02 DLLorenz Conversion to R--as sen slope only
	#    2011Oct25 DLLorenz Update for package
	#    2013Apr30 DLLorenz Bug fixes
	#    2014Dec29 DLLorenz Conversion to roxygen header
  ##
  ## Define the variance of Kendall's S function, required for conf. int.
  vark <- function(y, x) {
    ties.y <- rle(sort(y))$lengths
    ties.x <- rle(sort(x))$lengths
    n <- length(y)
    t1 <- n * (n - 1) * (2 * n + 5)
    ty2 <- sum(ties.y * (ties.y - 1) * (2 * ties.y + 5))
    tx2 <- sum(ties.x * (ties.x - 1) * (2 * ties.x + 5))
    v <- (t1 - ty2 -tx2)/18
    v1 <- sum(ties.y * (ties.y - 1)) * sum(ties.x * (ties.x - 1)) /
      (2 * n * (n - 1))
    v2 <- sum(ties.y * (ties.y - 1) * (ties.y - 2)) *
      sum(ties.x * (ties.x - 1) * (ties.x - 2)) /
        (9 * n * (n - 1) * (n - 2))
    v <- v + v1 + v2
    return (v)
  }
  ## Process formula as with regular linear regression!
  call <- match.call()
  m <- match.call(expand.dots = FALSE)
  m$intercept <- m$CI <- NULL
  m$drop.unused.levels <- TRUE
  m[[1]] <- as.name("model.frame")
  m <- eval(m, sys.parent())
  if(ncol(m) != 2L)
    stop("Must specify a single response and a single explanatory variable in the formula")
  ## Extract missing value info
  na.action <- attr(m, "na.action")
  y <- m[, 1L]
  yname <- names(m)[1L]
  x <- m[,2]
  xname <- names(m)[2L]
  n <- length(y)
  if (n < 3L)
    stop("model data should effectively be longer than 2.")  
  ## Calculate the statistics
  ## A fast, efficient way to compute all possible slopes:
  slopes <- unlist(lapply(seq(along = y), function(i, y, t)
                                    ((y[i] - y[1L:i]) / (t[i] - t[1L:i])), y, x))
  slopes <- sort(slopes) # removes missings (due to ties in x)
  sen.slope <- median(slopes)
  ## Compute the variance of S, accounting only for ties in x
  varS <- vark(seq(along=y), x) # Forces no ties in y
  Calpha <- -qnorm((1-CI)/2) * sqrt(varS)
  M1 <- as.integer((length(slopes) - Calpha)/2)
  M2 <- as.integer((length(slopes) + Calpha)/2) + 1
  sen.CI <- slopes[c(M1, M2)]
  names(sen.CI) <- paste(c("Lower", "Upper"),
                         substring(sprintf("%.2f", CI), 2), sep="") # drop 0
  ## Median of the data values.
  median.y <- median(y)         
  ## Median of the time values.
  median.x <- median(x)
  
  ## A line representing the trend of the data then is given by
  ##
  ##    y(t) = sen.slope*(t-med.time)+med.data
  ##
  ##    This line has the slope of the trend and passes through
  ##       the point (t=med.time, y=med.data)
  ## Compute the coefficients for the line: intercept and slope
  coef <- c(sen.slope*(-median.x)+median.y, sen.slope)
  fits <- coef[1L] + coef[2L]*x
  resids <- y - fits
  if(intercept == 'A1m') {
    coef[1L] <- coef[1L] + median(resids)
    resids <- y - coef[1L] - coef[2L]*x
  }
  ## Return the statistics.
  retval <- list(call=call, coefficients=coef, slope.CI=sen.CI, residuals=resids, 
                 fitted.values=fits, na.action=na.action, x=x, y=y, var.names=c(yname, xname),
                 model=m)
  oldClass(retval) <- "senSlope"
  return(retval)
}
```

```{r, eval = T, echo = T, warning = F, message = F}
### ------------------------------------------------------------------------------------------------------------ ###
#Plot local trend patterns for entire peatland sites
### ------------------------------------------------------------------------------------------------------------ ###
# theme for plotting
myTheme <- theme(legend.text = element_text(size = 10), 
                 legend.title = element_text(size = 10), 
                 legend.key.size = unit(1, 'cm'),
                 legend.position = 'bottom',
                 panel.grid.major = element_blank(), 
                 panel.background = element_rect(fill = "#cccccc"))
# colour palette for plotting
pal <- colorRampPalette(c('goldenrod3','goldenrod3','goldenrod3',"#f7c973","#f7c973", "#f7bf59", '#ecebeb', 'lightblue', "#209fb6", "#209fb6","#209fb6",'darkblue','darkblue','darkblue'))

# IDs of selcted peatland sites (filename)
all_site_ids=c('EU_1709986', 'EU_1755161', 'EU_1936806', 'EU_1710044', 'EU_2331582')
#all_site_ids=c('EU_1936807','EU_1936819','EU_1936813','EU_1936832')

#path to polygon shapes of all peatlands with ID attribute 
path_in = '/home/laurag/Arbeit/wwu/data/peatland/u2018_clc2018_v2020_20u1_geoPackage/DATA/'
all_peats=sf::st_read(paste0(path_in,'all_peatlands_small_size.shp'))

#id='EU_1709986'

#load forest & water mask
forest_mask=rast('/home/laurag/Arbeit/wwu/R/workspaces/satellite_ts_R/random_sample_analysis/copernicus/forest/FTY_2018_010m_eu_03035_v010/DATA/FTY_2018_010m_eu_03035_V1_0.tif')
water_mask=rast('/home/laurag/Arbeit/wwu/R/workspaces/satellite_ts_R/random_sample_analysis/copernicus/water/WAW_2018_010m_eu_03035_v020/DATA/WAW_2018_010m_eu_03035_V2_0.tif')

#load trend raster exported from GEE
path_peat_sites_tifs= '/home/laurag/Arbeit/wwu/R/workspaces/satellite_ts_R/random_sample_analysis/50singlepeats/exported_GEE/InterAct/'

#calculate summer mean (June-August) and filter trend raster basde on forest and water mask (outliers negligable, has been checked before)

lapply(all_site_ids, function(id){

#load raster stack with trend statistic individually per peatland site
    peat_rast=rast(paste0(path_peat_sites_tifs, id, '.tif'))
    peat_rast_summer_mean=mean(subset(peat_rast,grep('Sslope_jun',names(peat_rast), value = T)),
                           subset(peat_rast,grep('Sslope_jul',names(peat_rast), value = T)), 
                           subset(peat_rast,grep('Sslope_aug',names(peat_rast), value = T)))
    names(peat_rast_summer_mean)=c('summer_mean_trend')
    
    #replace pixels based on forest_mask & water mask
    peat_rast_summer_mean_proj=project(peat_rast_summer_mean, crs('epsg:3035'))
    forest_mask_crop=crop(forest_mask, peat_rast_summer_mean_proj, extend = T)
    water_mask_crop=crop(water_mask, peat_rast_summer_mean_proj)

    forest_mask_na=subst(forest_mask_crop,'all non-forest areas', NA)
    forest_mask_na=subst(forest_mask_na,'outside area', NA)
    forest_mask_na=subst(forest_mask_na,'broadleaved forest', 1)
    forest_mask_na=subst(forest_mask_na,'coniferous forest', 1)

    forest_mask_na_resamp=resample(forest_mask_na, peat_rast_summer_mean_proj, method='near')
    forest_mask_na_resamp_crop=crop(forest_mask_na_resamp,peat_rast_summer_mean_proj)
    forest_mask_na_resamp_crop=as.numeric(forest_mask_na_resamp_crop)

    water_mask_na_resamp=resample(water_mask_crop, peat_rast_summer_mean_proj, method='near')
    water_mask_na_resamp_crop=crop(water_mask_na_resamp,peat_rast_summer_mean_proj, snap = 'near', touches = T, mask=T)
    water_mask_na_resamp_crop=as.numeric(water_mask_na_resamp_crop)

    peat_rast_summer_mean_masked=mask(peat_rast_summer_mean_proj, forest_mask_na_resamp_crop,maskvalues=c(257), inverse=F,
      updatevalue=NA)
    peat_rast_summer_mean_masked=mask(peat_rast_summer_mean_masked, water_mask_na_resamp_crop, inverse=F, maskvalues=c(1,2), 
      updatevalue=NA)
    peat_shape=all_peats[which(all_peats$ID == id),]
    peat_rast_summer_mean_plot=crop(peat_rast_summer_mean_masked, peat_shape, snap = 'near', touches = T, mask=T)

    peat_rast_summer_mean_proj=project(peat_rast_summer_mean_plot, crs('epsg:4326'))


    ggplot() +
     geom_spatraster(data=peat_rast_summer_mean_proj) +
     facet_wrap(~lyr, ncol = 3) +
     scale_fill_stepsn(colours = pal(7), limits= c(-0.006,0.006), breaks =c(-0.006,-0.003,-0.001,0,0.001,0.003,0.006),na.value='#00000000') + 
     labs(colours = "Sens Slope")+ 
     geom_sf(data=peat_shape,colour= 'black', fill='#FF000000', size=1)+    
     labs(colour = "Sen's Slope [NDWI/yr] ")+ 
     ggtitle(id) + 
    myTheme
#ggsave(file = paste0('/home/laurag/Arbeit/wwu/R/workspaces/satellite_ts_R/random_sample_analysis/peats_swindles/selected_sites_plots/BjornRobroek/plots_indiv_sites/summer_mean_peats_trend_plots_',id,'_outline.svg'), 
#    width = 10, # The width of the plot in inches
#    height = 14)
})

```

## Supplementary
### Trend rasters for selected peatland sites and line plots of time series at one exemplary location within site

```{r, eval = T, echo = T, warning = F, message = F}
#### ----------------------------------------------------------------------------- ####
# NDWI trend raster: Plots of significant trends for selected sites for all month 
#### ----------------------------------------------------------------------------- ####

#to plot only significant trends p> 0.05 set p_val_filter to TRUE, otherwise to FALSE
p_val_filter=TRUE


lapply(all_site_ids, function(id){

    #load trend raster (Sen's Slope) per peatland site
    peat_rast=rast(paste0(path_peat_sites_tifs, id, '.tif'))

#to plot only significant trends p> 0.05
    if(p_val_filter==T){
    peat_rast_Sslope_proj_statmasked=lapply(seq(from=5,to=10), function(m){
        peat_rast_Sslope_proj_m=subset(peat_rast,grep(paste0('Sslope_', tolower(month.abb[m])), names(peat_rast)))
        peat_rast_pval_m = subset(peat_rast,grep(paste0('p_val_', tolower(month.abb[m])), names(peat_rast)))
        peat_rast_count_m = subset(peat_rast,grep(paste0('count_', tolower(month.abb[m])), names(peat_rast)))
        peat_rast_pval_m[which(peat_rast_pval_m[]>0.05)]<-NA
        peat_rast_count_m[which(peat_rast_count_m[]<10)]<-NA
        peat_rast_Sslope_proj_pvmasked=mask(peat_rast_Sslope_proj_m, peat_rast_pval_m, inverse=F, maskvalues=NA, updatevalue=NA)
        peat_rast_Sslope_proj_comasked=mask(peat_rast_Sslope_proj_pvmasked, peat_rast_count_m, inverse=F, maskvalues=NA, updatevalue=NA)
        return(peat_rast_Sslope_proj_comasked)
    })
    peat_rast=rast(peat_rast_Sslope_proj_statmasked)
    }

    peat_rast_Sslope=subset(peat_rast, grep('Sslope', names(peat_rast), value = T))

    #masking water, forest, outline
    peat_rast_Sslope_proj=project(peat_rast_Sslope, crs('epsg:3035'))
    forest_mask_crop=crop(forest_mask, peat_rast_Sslope_proj, extend = T)
    water_mask_crop=crop(water_mask, peat_rast_Sslope_proj)

    forest_mask_na=subst(forest_mask_crop,'all non-forest areas', NA)
    forest_mask_na=subst(forest_mask_na,'outside area', NA)
    forest_mask_na=subst(forest_mask_na,'broadleaved forest', 1)
    forest_mask_na=subst(forest_mask_na,'coniferous forest', 1)

    forest_mask_na_resamp=resample(forest_mask_na, peat_rast_Sslope_proj, method='near')
    forest_mask_na_resamp_crop=crop(forest_mask_na_resamp,peat_rast_Sslope_proj)
    forest_mask_na_resamp_crop=as.numeric(forest_mask_na_resamp_crop)
    water_mask_na_resamp=resample(water_mask_crop, peat_rast_Sslope_proj, method='near')
    
    water_mask_na_resamp_crop=crop(water_mask_na_resamp,peat_rast_Sslope_proj, snap = 'near', touches = T, mask=T)
    water_mask_na_resamp_crop=as.numeric(water_mask_na_resamp_crop)
    peat_rast_Sslope_masked=mask(peat_rast_Sslope_proj, forest_mask_na_resamp_crop,maskvalues=c(257), inverse=F,
    updatevalue=NA)
    peat_rast_Sslope_masked=mask(peat_rast_Sslope_masked, water_mask_na_resamp_crop, inverse=F, maskvalues=c(1,2), 
    updatevalue=NA)

    peat_shape=all_peats[which(all_peats$ID == id),]
    peat_rast_Sslope_plot=crop(peat_rast_Sslope_masked, peat_shape, snap = 'near', touches = T, mask=T)

#plot(peat_rast_Sslope_plot)
    peat_rast_Sslope_proj=project(peat_rast_Sslope_plot, crs('epsg:4326'))

#rename layer for facet wrapped plot
    rename_lookup_l=lapply(seq(from=5, to=10), function(m){
    rename_lookup=names(peat_rast_Sslope_proj)[grep(paste0('Sslope_', tolower(month.abb[m])), names(peat_rast_Sslope_proj))]
    if(length(rename_lookup)==0){
      rename_lookup=NA
    }
      return(rename_lookup)
    })
    rename_lookup_v=as.data.frame(cbind(new= month.name[5:10], old = do.call(rbind,rename_lookup_l)))
    colnames(rename_lookup_v)=c('new','old')

    recode_vec =setNames(rename_lookup_v$old, rename_lookup_v$new)
    if(length(which(is.na(recode_vec)))!=0){
      recode_vec=recode_vec[-which(is.na(recode_vec))]
    }
    peat_rast_Sslope_proj=peat_rast_Sslope_proj %>%
      rename(!!! recode_vec)

    peat_rast_Sslope_proj_MO=peat_rast_Sslope_proj[[which(names(peat_rast_Sslope_proj) %in% c(month.name[5:10]))]]
    #names(peat_rast_Sslope_proj)
    
    ggplot() +
     geom_spatraster(data=peat_rast_Sslope_proj_MO) +
     facet_wrap(~lyr, ncol = 3) +
     scale_fill_stepsn(colours = pal(7), limits= c(-0.006,0.006), breaks =c(-0.006,-0.003,-0.001,0,0.001,0.003,0.006),na.value='#00000000') + 

     geom_sf(data=peat_shape,colour= 'black', fill='#FF000000', size=1)+ 
     scale_x_continuous(breaks = seq(-30, 30, by = 0.05))+
     ggtitle(id)+ 
    myTheme
#ggsave(file = paste0('/home/laurag/Arbeit/wwu/R/workspaces/satellite_ts_R/random_sample_analysis/peats_swindles/selected_sites_plots/BjornRobroek/plots_indiv_sites/MO_month_ov_peats_trend_plots_significant',id,'.svg'), 
#    width = 10, # The width of the plot in inches
#    height = 14) 
})



#### ---------------------------------------------------------------- ####
# NDWI timeseries: Line plots plus trends
#### ---------------------------------------------------------------- ####

#load rasters stacks containing median NDWI time series (41 years ~ max 41 layers) for each month
ts_rast_path='/home/laurag/Arbeit/wwu/R/workspaces/satellite_ts_R/random_sample_analysis/ndwi_tif_after_snow/selected_final_paper/'

trend_path=path_peat_sites_tifs #'/home/laurag/Arbeit/wwu/R/workspaces/satellite_ts_R/random_sample_analysis/50singlepeats/exported_GEE/InterAct/'
points_path='/home/laurag/Arbeit/wwu/R/workspaces/satellite_ts_R/random_sample_analysis/ndwi_tif_after_snow/selected_sites_final_paper_extr.gpkg'
points_extr=st_read(points_path)

#l=1

lapply(seq(length(all_site_ids)), function(l){
    ts_list=list.files(paste0(ts_rast_path,all_site_ids[l]), pattern = '*.tif$', full.names=TRUE)
    ts_list_rast=lapply(ts_list, rast)
    stack_rast=rast(ts_list_rast)

    #extract time series at one selcted point (selected based on: maximum number of significant trends) for each site
    point_id=points_extr %>% filter(ID == all_site_ids[l])


    val_extracted_pt=lapply(seq(dim(stack_rast)[3]),function(b){
        band=stack_rast[[b]]
        n=names(band)
        ex = terra::extract(band, point_id, xy=T, na.rm=TRUE)
        year=as.numeric(substr(str_split(n, '_')[[1]][2], 1,4))
        month=as.numeric(str_split(str_split(n, '_')[[1]][2], '-')[[1]][2])
        result = data.frame(Year=year,Month=month,NDWI=ex[,2], x=ex[,3], y=ex[,4])
        return(result)
    })
    ts_extracted_pt=as.data.frame(do.call(rbind,val_extracted_pt))
    ts_extracted_pt[,2]=as.factor(ts_extracted_pt[,2])

    ###--------------------------------###
    ### iterate over months
    ###--------------------------------###

    #plot slope and NDWI timeseries per month with significant trend
    list_trend_model_data=lapply(unique(ts_extracted_pt$Month), function(month_i){   #

      filtered_ts_mon= ts_extracted_pt %>% filter(Month == month_i)
      filtered_ts_mon_nona=na.omit(filtered_ts_mon)

      if(as.numeric(as.character(month_i))<11 & as.numeric(as.character(month_i))>4){

        sens_USGS_sig_mon=senSlope(NDWI ~ Year, data=filtered_ts_mon, na.action = na.exclude)
        filtered_ts_df=as.data.frame(cbind(filtered_ts_mon_nona, fit=sens_USGS_sig_mon$fitted.values, Month_n=rep(month.abb[as.numeric(as.character(month_i))], length(sens_USGS_sig_mon$fitted.values))))

        if(sens_USGS_sig_mon$coefficients[2]>0){
          col_vec_np=c("#2d2e30", "darkcyan")
        }else{
          col_vec_np=c("#2d2e30", "#b48306")
        }

        ggplot(filtered_ts_mon[!is.na(filtered_ts_mon$NDWI), ])+
          geom_function(fun = ~ sens_USGS_sig_mon$coefficients[2]*.x+sens_USGS_sig_mon$coefficients[1], aes(color='Trend'), linewidth=1.5)+
          geom_line( aes(x=Year, y=NDWI, color = 'NDWI'), linewidth = 1.5)+ #  

          theme_light()+
          theme(legend.position="top", axis.text=element_text(size=12),
            axis.title=element_text(size=14,face="bold"), plot.title = element_text(size=18),
            legend.text = element_text(size = 14), legend.title = element_text(size = 12), 
            legend.key.size = unit(1.5, 'cm'))+
          ylim(-0.55,0.55)+
          xlim(1982,2022)+
          scale_colour_manual("",values=col_vec_np)+
          annotate(geom="text", x=2013, y=-0.5, label=paste0('Sens Slope [NDWI/yr] = ',round(sens_USGS_sig_mon$coefficients[2], digits=5)), size=3)+
          geom_hline(yintercept=0.0, color='#323233')+
          geom_point(aes(x=Year, y=NDWI, color = 'NDWI'), size = 2)+
          ggtitle(paste0(all_site_ids[l], ' ',month.name[as.numeric(as.character(month_i))], ' x=', round(st_coordinates(st_geometry(point_id))[,1], digits = 5), ' y=', round(st_coordinates(st_geometry(point_id))[,2], digits = 5)))

#ggsave(file = paste0(path_plots, 'line_plots/lplot_trendts_', all_site_ids[l], '_', month.name[as.numeric(as.character(month_i))], '.svg'),
#   width = 10, # The width of the plot in inches
#   height = 5)  
      }
#return(filtered_ts_df)
    })

})

```
```{r, echo =F, eval = F, echo = F}
trend_model_data=do.call(rbind, list_trend_model_data)
trend_model_data[,7]=factor(trend_model_data$Month_n, levels = month.abb)
#plot all significant lines together
df_pal12 <- c("Jan"="blue","Feb"='lightblue', "Mar"='khaki2',"Apr"='gold', "May"='orange', "Jun"='#089708', "Jul"='chartreuse3',"Aug"='darkgreen', "Sep"='coral3', "Oct"='darkred', "Nov"='brown',"Dec"='darkblue')
#df_pal12=c('Jan'=df_pal12)
#colnames(df_pal12) = month.abb
#names(df_pal12)

#filtered_yr_sf$Month = factor(filtered_yr_sf$Month, levels = month.name)

ggplot()+
  #geom_function(fun = ~ sens_USGS_sig_mon$coefficients[2]*.x+sens_USGS_sig_mon$coefficients[1], aes(color='Trend'), size=2)+
  geom_line(data= as.data.frame(cbind(Year=trend_model_data$Year,Month_n=trend_model_data$Month_n, Trend=trend_model_data$fit)), aes(x=Year, y=Trend, group = Month_n), size=1, color= 'grey') + 
  geom_line(data=trend_model_data, aes(x=Year, y=NDWI, group = Month_n, color = Month_n), size = 1)+ #
  geom_point(data= trend_model_data, aes(x=Year, y=NDWI, group = Month_n, color = Month_n), size = 1)+ 
  #labs(color = paste0(month.name[sig_mon],'_NDWI')) +
  theme_light()+
  theme(legend.position="right", axis.text=element_text(size=14),
        axis.title=element_text(size=16,face="bold"), plot.title = element_text(size=22),
        legend.text = element_text(size = 16), legend.title = element_text(size = 14), 
        legend.key.size = unit(0.7, 'cm'))+
  ylim(-1,1)+
  xlim(1982,2022)+
  ylab('NDWI')+
  scale_colour_manual('Month', values =df_pal12 )+ #pal2(length(unique(trend_model_data$Month)))
  ggtitle(paste0('Significant NDWI Trends (', vect_peat_ids[id], ')'))

if (file.exists(paste0(path_tifs, 'plots_out_ylim/', vect_peat_ids[id]))){
    print(vect_peat_ids[id])
} else {
    dir.create(file.path(path_tifs, 'plots_out_ylim/', vect_peat_ids[id]))  
}
```